name: YoSinTV Future TV Listings

on:
  schedule:
    # 00:00 UTC and 12:00 UTC daily
    - cron: '0 0,12 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install curl_cffi pycountry

      - name: Run Scraper
        run: |
          python future_scraper.py

      - name: Commit Updated JSON Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add -A

          git diff --cached --quiet && exit 0

          git commit -m "Update future TV listings"

          git push
